name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        node-version: ["16"]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: make build
        shell: bash
      - name: Lint
        run: make lint
        shell: bash
      - name: List
        run: make list
        shell: bash
