name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    steps:
      - uses: actions/checkout@v3
      - name: Configure Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}

      - name: Deps
        run: make deps

      - name: Build
        run: make build

      - name: Lint
        run: make lint
